#development version

version: "3.3"
services:
  web:
    image: nginx:1.21.3
    ports:
      - "8080:80"
    volumes:
      - ../src:/code
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  php:
    build: ./php
    volumes:
      - ../src:/code
      
  mysql:
    image: mysql:8.0.27
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: project1
    volumes:
      - ./mysql/docker.cnf:/etc/mysql/conf.d/docker.cnf
    ports:
      - "3308:3306"