web:
  image: nginx:latest
  ports:
    - "8080:80"
  volumes:
    - ../src:/code
    - ./nginx/site.conf:/etc/nginx/conf.d/site.conf
  links:
    - php
php:
  build: ./php
  volumes:
    - ../src:/code