version: "3.3"
services:
  web:
    image: nginx:1.21.3
    ports:
      - "80:80"
    volumes:
      - ../src:/code
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  php:
    build: ./php
    volumes:
      - ../src:/code